// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex

package org.practice1.Lexer;

import java_cup.runtime.*;
import org.practice1.Cup.ParserSym;
import org.practice1.Errors.*;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\24\u0200\1\u0300\11\u0200\1\u0400\17\u0200\1\u0500"+
    "\u10cf\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\5\1\22\0\1\1\7\0\1\2\1\3\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\12\12\7\0\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\22\1\25\1\26\1\27\1\30\1\31\1\22"+
    "\1\32\1\33\1\34\1\35\1\36\3\22\1\37\4\0"+
    "\1\22\1\0\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\22\1\25\1\26\1\27"+
    "\1\30\1\31\1\22\1\32\1\33\1\34\1\35\1\36"+
    "\3\22\1\37\12\0\1\1\32\0\1\1\217\0\2\40"+
    "\115\0\1\41\u0200\0\1\1\177\0\13\1\35\0\2\1"+
    "\5\0\1\1\57\0\1\1\240\0\1\1\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\1\1\11\1\12\12\13\1\14\2\0\6\13"+
    "\1\0\2\13\1\0\7\13\1\0\1\14\3\13\1\0"+
    "\5\13\1\0\2\13\1\0\1\13\1\0\7\13\1\0"+
    "\4\13\1\0\1\15\4\13\1\0\1\13\2\16\1\13"+
    "\1\0\4\13\1\0\1\13\1\17\1\13\1\0\2\13"+
    "\1\0\2\13\1\0\1\13\1\0\2\13\1\20\1\0"+
    "\1\13\1\0\2\21\1\13\1\22\2\13\1\0\2\13"+
    "\1\0\1\23\1\13\1\0\1\24\1\13\1\0\1\24"+
    "\1\13\1\0\2\13\1\0\1\13\1\0\1\13\1\25"+
    "\1\13\1\0\1\13\2\26\1\13\1\0\1\13\1\0"+
    "\2\27\1\30\1\13\1\30\1\13\1\0\1\31\1\13"+
    "\1\0\1\13\2\32\2\33\1\34\2\35\2\36\2\13"+
    "\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\42\0\42\0\42\0\42\0\42"+
    "\0\42\0\146\0\42\0\210\0\252\0\314\0\356\0\u0110"+
    "\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba\0\u01dc\0\u01fe\0\146"+
    "\0\u0220\0\u0242\0\u0264\0\u0286\0\u02a8\0\u02ca\0\u02ec\0\u030e"+
    "\0\u0330\0\u0352\0\u0374\0\u0396\0\u03b8\0\u03da\0\u03fc\0\u041e"+
    "\0\u0440\0\u0462\0\u0484\0\u0484\0\u04a6\0\u04c8\0\u04ea\0\u050c"+
    "\0\u052e\0\u0550\0\u0572\0\u0594\0\u05b6\0\u05d8\0\u05fa\0\u061c"+
    "\0\u063e\0\u0660\0\u0682\0\u06a4\0\u06c6\0\u06e8\0\u070a\0\u072c"+
    "\0\u074e\0\u0770\0\u0792\0\u07b4\0\u07d6\0\u07f8\0\u081a\0\u083c"+
    "\0\314\0\u085e\0\u0880\0\u08a2\0\u08c4\0\u08e6\0\u0908\0\314"+
    "\0\42\0\u092a\0\u094c\0\u096e\0\u0990\0\u09b2\0\u09d4\0\u09f6"+
    "\0\u0a18\0\314\0\u0a3a\0\u0a5c\0\u0a7e\0\u0aa0\0\u0ac2\0\u0ae4"+
    "\0\u0b06\0\u0b28\0\u0b4a\0\u0b6c\0\u0b8e\0\u0bb0\0\314\0\u0bd2"+
    "\0\u0bf4\0\u0c16\0\314\0\42\0\u0c38\0\314\0\u0c5a\0\u0c7c"+
    "\0\u0c9e\0\u0cc0\0\u0ce2\0\u0d04\0\314\0\u0d26\0\u0d48\0\314"+
    "\0\u0d6a\0\u0d8c\0\42\0\u0dae\0\u0dd0\0\u0df2\0\u0e14\0\u0e36"+
    "\0\u0e58\0\u0e7a\0\u0e9c\0\314\0\u0ebe\0\u0ee0\0\u0f02\0\314"+
    "\0\42\0\u0f24\0\u0f46\0\u0f68\0\u0f8a\0\314\0\42\0\314"+
    "\0\u0fac\0\42\0\u0fce\0\u0ff0\0\314\0\u1012\0\u1034\0\u1056"+
    "\0\314\0\42\0\314\0\42\0\314\0\314\0\42\0\314"+
    "\0\42\0\u1078\0\u109a\0\314";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\3\16\1\20"+
    "\3\16\1\21\1\16\1\22\1\23\1\24\1\25\3\16"+
    "\1\26\1\16\2\2\43\0\1\3\52\0\1\27\37\0"+
    "\1\30\1\0\1\14\4\0\1\31\34\0\14\16\1\32"+
    "\1\33\7\16\1\34\14\0\26\16\14\0\5\16\1\35"+
    "\3\16\1\36\11\16\1\37\2\16\1\40\13\0\20\16"+
    "\1\41\5\16\14\0\11\16\1\42\14\16\1\43\13\0"+
    "\1\16\1\44\3\16\1\45\20\16\14\0\2\16\1\46"+
    "\23\16\14\0\16\16\1\47\7\16\14\0\5\16\1\50"+
    "\10\16\1\51\7\16\14\0\5\16\1\52\20\16\14\0"+
    "\1\27\4\0\1\31\27\0\1\53\1\0\1\53\2\0"+
    "\1\54\41\0\1\16\1\55\24\16\14\0\11\16\1\56"+
    "\10\16\1\57\3\16\1\60\13\0\23\16\1\61\2\16"+
    "\14\0\13\16\1\62\12\16\14\0\20\16\1\63\5\16"+
    "\14\0\1\16\1\64\16\16\1\65\5\16\34\0\1\66"+
    "\21\0\1\16\1\67\7\16\1\70\14\16\1\71\13\0"+
    "\15\16\1\72\10\16\31\0\1\73\24\0\20\16\1\74"+
    "\5\16\14\0\7\16\1\75\16\16\14\0\12\16\1\76"+
    "\13\16\14\0\13\16\1\77\12\16\14\0\3\16\1\100"+
    "\22\16\14\0\12\16\1\101\6\16\1\102\4\16\1\0"+
    "\1\103\12\0\20\16\1\104\5\16\14\0\1\54\41\0"+
    "\20\16\1\105\5\16\14\0\14\16\1\106\11\16\14\0"+
    "\5\16\1\107\20\16\30\0\1\110\25\0\13\16\1\111"+
    "\12\16\14\0\5\16\1\112\20\16\14\0\3\16\1\113"+
    "\22\16\14\0\4\16\1\114\21\16\14\0\24\16\1\115"+
    "\1\16\17\0\1\116\36\0\6\16\1\117\17\16\14\0"+
    "\21\16\1\120\4\16\1\0\1\121\33\0\1\121\5\0"+
    "\1\121\12\0\5\16\1\122\20\16\21\0\1\123\34\0"+
    "\1\16\1\124\24\16\14\0\20\16\1\125\5\16\14\0"+
    "\5\16\1\126\20\16\14\0\11\16\1\127\14\16\1\130"+
    "\13\0\22\16\1\131\3\16\14\0\16\16\1\132\7\16"+
    "\14\0\1\16\1\133\24\16\15\0\1\134\40\0\4\16"+
    "\1\135\21\16\14\0\11\16\1\136\14\16\1\137\13\0"+
    "\1\16\1\140\24\16\14\0\20\16\1\141\5\16\15\0"+
    "\1\142\40\0\21\16\1\143\4\16\1\0\1\144\12\0"+
    "\23\16\1\145\2\16\14\0\20\16\1\146\5\16\14\0"+
    "\1\16\1\147\24\16\37\0\1\150\16\0\11\16\1\151"+
    "\14\16\1\152\13\0\1\16\1\153\24\16\15\0\1\154"+
    "\40\0\15\16\1\155\10\16\14\0\16\16\1\156\7\16"+
    "\14\0\22\16\1\157\3\16\14\0\7\16\1\160\16\16"+
    "\23\0\1\161\32\0\1\16\1\162\24\16\14\0\4\16"+
    "\1\163\21\16\20\0\1\164\35\0\5\16\1\165\20\16"+
    "\14\0\13\16\1\166\12\16\27\0\1\167\26\0\20\16"+
    "\1\170\5\16\14\0\11\16\1\171\14\16\1\172\33\0"+
    "\1\173\21\0\22\16\1\174\3\16\36\0\1\175\17\0"+
    "\13\16\1\176\12\16\14\0\1\16\1\177\24\16\27\0"+
    "\1\200\26\0\3\16\1\201\22\16\17\0\1\202\36\0"+
    "\12\16\1\203\13\16\14\0\16\16\1\204\7\16\14\0"+
    "\16\16\1\205\7\16\32\0\1\206\23\0\15\16\1\207"+
    "\10\16\14\0\16\16\1\210\7\16\32\0\1\211\23\0"+
    "\13\16\1\212\12\16\27\0\1\213\26\0\16\16\1\214"+
    "\7\16\32\0\1\215\23\0\5\16\1\216\20\16\21\0"+
    "\1\217\34\0\16\16\1\220\7\16\14\0\4\16\1\221"+
    "\21\16\32\0\1\222\23\0\1\16\1\223\24\16\15\0"+
    "\1\224\40\0\1\16\1\225\24\16\14\0\15\16\1\226"+
    "\10\16\31\0\1\227\24\0\7\16\1\230\16\16\14\0"+
    "\16\16\1\231\7\16\32\0\1\232\23\0\20\16\1\233"+
    "\5\16\34\0\1\234\21\0\16\16\1\235\7\16\14\0"+
    "\20\16\1\236\5\16\34\0\1\237\21\0\16\16\1\240"+
    "\7\16\32\0\1\241\23\0\23\16\1\242\2\16\14\0"+
    "\13\16\1\243\12\16\14\0\16\16\1\244\7\16\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4284];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\6\11\1\1\1\11\14\1\2\0"+
    "\6\1\1\0\2\1\1\0\7\1\1\0\4\1\1\0"+
    "\5\1\1\0\2\1\1\0\1\1\1\0\7\1\1\0"+
    "\4\1\1\0\5\1\1\0\2\1\1\11\1\1\1\0"+
    "\4\1\1\0\3\1\1\0\2\1\1\0\2\1\1\0"+
    "\1\1\1\0\3\1\1\0\1\1\1\0\1\1\1\11"+
    "\4\1\1\0\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\1\11\1\1\1\0\2\1\1\0\1\1\1\0\3\1"+
    "\1\0\2\1\1\11\1\1\1\0\1\1\1\0\1\1"+
    "\1\11\2\1\1\11\1\1\1\0\2\1\1\0\2\1"+
    "\1\11\1\1\1\11\2\1\1\11\1\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
        StringBuffer stringBuffer = new StringBuffer();
        ArrayList<ErrorL> errors = new ArrayList<ErrorL>();

        private Symbol symbol(int type){
            return new Symbol(type, yyline+1, yycolumn+1);
        }

        private Symbol symbol(int type, Object value){
            return new Symbol(type, yyline+1, yycolumn+1, value);
        }
/*
        private addError(String message){
            errors.add(new ErrorL(yyline+1, yycolumn+1, "No se reconoce este simbolo", 0, message));
        }
*/


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return new Symbol(ParserSym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /*addError(yytext());*/
            }
          // fall through
          case 32: break;
          case 2:
            { /*ignore*/
            }
          // fall through
          case 33: break;
          case 3:
            { return new Symbol(ParserSym.LPAREN, yycolumn, yyline, yytext());
            }
          // fall through
          case 34: break;
          case 4:
            { return new Symbol(ParserSym.RPAREN, yycolumn, yyline, yytext());
            }
          // fall through
          case 35: break;
          case 5:
            { return new Symbol(ParserSym.ASTHERISK, yycolumn, yyline, yytext());
            }
          // fall through
          case 36: break;
          case 6:
            { return new Symbol(ParserSym.PLUS, yycolumn, yyline, yytext());
            }
          // fall through
          case 37: break;
          case 7:
            { return new Symbol(ParserSym.COMMA, yytext());
            }
          // fall through
          case 38: break;
          case 8:
            { return new Symbol(ParserSym.MINUS, yycolumn, yyline, yytext());
            }
          // fall through
          case 39: break;
          case 9:
            { return new Symbol(ParserSym.DIVISION, yycolumn, yyline, yytext());
            }
          // fall through
          case 40: break;
          case 10:
            { return new Symbol(ParserSym.NUMBER, yytext());
            }
          // fall through
          case 41: break;
          case 11:
            { return new Symbol(ParserSym.NAME, yytext());
            }
          // fall through
          case 42: break;
          case 12:
            { return new Symbol(ParserSym.REAL, yytext());
            }
          // fall through
          case 43: break;
          case 13:
            { return new Symbol(ParserSym.BLUE, yytext());
            }
          // fall through
          case 44: break;
          case 14:
            { return new Symbol(ParserSym.GRAY, yytext());
            }
          // fall through
          case 45: break;
          case 15:
            { return new Symbol(ParserSym.RED, yytext());
            }
          // fall through
          case 46: break;
          case 16:
            { return new Symbol(ParserSym.CURVE, yytext());
            }
          // fall through
          case 47: break;
          case 17:
            { return new Symbol(ParserSym.LINE, yytext());
            }
          // fall through
          case 48: break;
          case 18:
            { return new Symbol(ParserSym.BLACK, yytext());
            }
          // fall through
          case 49: break;
          case 19:
            { return new Symbol(ParserSym.GREEN, yytext());
            }
          // fall through
          case 50: break;
          case 20:
            { return new Symbol(ParserSym.ANIMATE, yytext());
            }
          // fall through
          case 51: break;
          case 21:
            { return new Symbol(ParserSym.OBJECTO, yytext());
            }
          // fall through
          case 52: break;
          case 22:
            { return new Symbol(ParserSym.PINK, yytext());
            }
          // fall through
          case 53: break;
          case 23:
            { return new Symbol(ParserSym.CYAN, yytext());
            }
          // fall through
          case 54: break;
          case 24:
            { return new Symbol(ParserSym.CIRCLE, yytext());
            }
          // fall through
          case 55: break;
          case 25:
            { return new Symbol(ParserSym.ORANGE, yytext());
            }
          // fall through
          case 56: break;
          case 26:
            { return new Symbol(ParserSym.YELLOW, yytext());
            }
          // fall through
          case 57: break;
          case 27:
            { return new Symbol(ParserSym.PREVIOUS, yytext());
            }
          // fall through
          case 58: break;
          case 28:
            { return new Symbol(ParserSym.SQUARE, yytext());
            }
          // fall through
          case 59: break;
          case 29:
            { return new Symbol(ParserSym.GRAPH, yytext());
            }
          // fall through
          case 60: break;
          case 30:
            { return new Symbol(ParserSym.POLYGON, yytext());
            }
          // fall through
          case 61: break;
          case 31:
            { return new Symbol(ParserSym.RECTANGLE, yytext());
            }
          // fall through
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
